# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MyDem0cracy.ca
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  How do you think Canada’s democracy should work? D’après vous, comment la
  démocratie du Canada devrait-elle fonctionner?
#baseurl: "/MyDem0cracy.ca-site" # the subpath of your site, e.g. /blog
url: "mydem0cracy.ca" # the base hostname & protocol for your site
twitter_username:
github_username:  CivicTechTO/MyDem0cracy.ca-site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-77242163-1
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

polis:
  conversation_id: 69fnuffbkm

mydem0cracy:
  text:
    sub_title: >-
      MyDem0cracy.ca is an innovative way to join the national conversation on
      electoral reform. By answering a few questions, you can draw a picture of
      your democratic values. You can share your results with friends. It only
      takes a few minutes to answer and your feedback will help shape a
      healthier democracy.
    welcome_message: >-
      As you answer the questions, remember that there are no wrong answers and
      your individual responses will always remain anonymous. This is a
      different way of consulting Canadians – we hope you enjoy this, and learn
      something too. Thank you for participating.
    question_permission: >-
      If you are under 16 years of age, please speak to your parent or guardian
      to get their agreement before you begin the MyDem0cracy.ca experience.

methodology: |
  ### Seed comments

  We setup the initial consultation process with a set of seed comments to kick-start the conversation. These seed comments were derived from statements mentioned in the MPs reports from their respective town hall meetings on electoral reform which can be found [here](http://www.parl.gc.ca/Content/HOC/Committee/421/ERRE/WebDoc/WD8405589/Members_Reports-e.html).

  ### How commenting works

  We invite you to share your own perspectives. Once you have expressed your agreement/disagreement or passed on all statements, feel free to submit a statement of your own if you feel that it is an essential piece to the national conversation about electoral reform.

  ### Why moderate the conversation?

  We are using a strict moderation process where all comments will first be approved before being visible to other visitors of mydem0cracy.ca. We are using this moderation process to reduce repetitive statements and to assure all statements are relevant to the conversation. We will release all submitted statements as part of our open data policy in order to be as transparent as possible about how statements were moderated.
